#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun Jun 25 10:28:19 2023
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MyFrame import MyFrame


class MyApp(wx.App):
        def OnInit(self):
                self.frame = MyFrame(None, wx.ID_ANY, "")
                self.SetTopWindow(self.frame)
                self.frame.Show()
                return True

# end of class MyApp

if __name__ == "__main__":
        app = MyApp(0)
        app.MainLoop()
