# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Fri Jun 23 23:05:45 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class DialogNewConnection(wx.Dialog):
        def __init__(self, *args, **kwds):
                # begin wxGlade: DialogNewConnection.__init__
                kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
                wx.Dialog.__init__(self, *args, **kwds)
                self.SetTitle("New Connection")

                sizer_1 = wx.BoxSizer(wx.VERTICAL)

                sizer_3 = wx.BoxSizer(wx.VERTICAL)
                sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 4)

                sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
                sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

                label_3 = wx.StaticText(self, wx.ID_ANY, "Name", style=wx.ALIGN_RIGHT)
                label_3.SetMinSize((50, 16))
                sizer_4.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                self.txtName = wx.TextCtrl(self, wx.ID_ANY, "")
                sizer_4.Add(self.txtName, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
                sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

                label_4 = wx.StaticText(self, wx.ID_ANY, "Host", style=wx.ALIGN_RIGHT)
                label_4.SetMinSize((50, 16))
                sizer_5.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                self.txtHost = wx.TextCtrl(self, wx.ID_ANY, "")
                sizer_5.Add(self.txtHost, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
                sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

                label_5 = wx.StaticText(self, wx.ID_ANY, "Port", style=wx.ALIGN_RIGHT)
                label_5.SetMinSize((50, 16))
                sizer_6.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                self.txtPort = wx.TextCtrl(self, wx.ID_ANY, "")
                self.txtPort.SetMinSize((80, 23))
                sizer_6.Add(self.txtPort, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

                sizer_2 = wx.StdDialogButtonSizer()
                sizer_1.Add(sizer_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

                self.button_OK = wx.Button(self, wx.ID_OK, "")
                self.button_OK.SetDefault()
                sizer_2.AddButton(self.button_OK)

                self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
                sizer_2.AddButton(self.button_CANCEL)

                sizer_2.Realize()

                self.SetSizer(sizer_1)
                sizer_1.Fit(self)

                self.SetAffirmativeId(self.button_OK.GetId())
                self.SetEscapeId(self.button_CANCEL.GetId())

                self.Layout()
                # end wxGlade

# end of class DialogNewConnection
