# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Fri Jun 23 09:59:42 2023
#

import wx
# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
        def __init__(self, *args, **kwds):
                # begin wxGlade: MyFrame.__init__
                kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
                wx.Frame.__init__(self, *args, **kwds)
                self.SetSize((950, 666))
                self.SetTitle("frame")

                # Menu Bar
                self.frame_menubar = wx.MenuBar()
                wxglade_tmp_menu = wx.Menu()
                self.frame_menubar.Append(wxglade_tmp_menu, "&File")
                wxglade_tmp_menu = wx.Menu()
                self.frame_menubar.Append(wxglade_tmp_menu, "&Edit")
                wxglade_tmp_menu = wx.Menu()
                self.frame_menubar.Append(wxglade_tmp_menu, "&Options")
                self.SetMenuBar(self.frame_menubar)
                # Menu Bar end

                self.panel_1 = wx.Panel(self, wx.ID_ANY)

                sizer_1 = wx.BoxSizer(wx.VERTICAL)

                sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
                sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)

                def onConnections():
                  with DialogConnections(self) as dialogConnections:
                    showModal()
                self.btnConnections = wx.Button(self.panel_1, wx.ID_ANY, "Connections")
                sizer_2.Add(self.btnConnections, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.FIXED_MINSIZE | wx.LEFT | wx.TOP, 5)

                self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "button_2")
                sizer_2.Add(self.button_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 5)

                self.window_1 = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
                self.window_1.SetMinimumPaneSize(20)
                sizer_1.Add(self.window_1, 1, wx.ALL | wx.EXPAND, 0)

                self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)
                self.window_1_pane_1.SetBackgroundColour(wx.Colour(192, 192, 192))

                sizer_3 = wx.BoxSizer(wx.VERTICAL)

                label_1 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "Databases")
                sizer_3.Add(label_1, 0, wx.LEFT | wx.RIGHT, 4)

                self.list_box_1 = wx.ListBox(self.window_1_pane_1, wx.ID_ANY, choices=["choice 1"])
                sizer_3.Add(self.list_box_1, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 4)

                label_2 = wx.StaticText(self.window_1_pane_1, wx.ID_ANY, "Collections")
                sizer_3.Add(label_2, 0, wx.LEFT | wx.RIGHT, 4)

                self.list_box_2 = wx.ListBox(self.window_1_pane_1, wx.ID_ANY, choices=["choice 1"])
                sizer_3.Add(self.list_box_2, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 4)

                self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

                sizer_4 = wx.BoxSizer(wx.VERTICAL)

                self.notebook_1 = wx.Notebook(self.window_1_pane_2, wx.ID_ANY)
                sizer_4.Add(self.notebook_1, 0, wx.EXPAND, 0)

                self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
                self.notebook_1.AddPage(self.notebook_1_pane_1, "notebook_1_pane_1")

                self.grid_1 = wx.grid.Grid(self.window_1_pane_2, wx.ID_ANY, size=(1, 1))
                self.grid_1.CreateGrid(10, 0)
                sizer_4.Add(self.grid_1, 1, wx.EXPAND, 0)

                self.window_1_pane_2.SetSizer(sizer_4)

                self.window_1_pane_1.SetSizer(sizer_3)

                self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2, 204)

                self.panel_1.SetSizer(sizer_1)

                self.Layout()

                self.Bind(wx.EVT_BUTTON, self.onConnections, self.btnConnections)
                # end wxGlade

        def onConnections(self, event):  # wxGlade: MyFrame.<event_handler>
                print("Event handler 'onConnections' not implemented!")
                event.Skip()
# end of class MyFrame
